### ISSUE TITLE
Error on yarn dev or yarn start.

### ISSUE THREAD

**Issue by Taramouse** [jonaskuiler/universal-vue-app-with-graphql#1]
Hi Jonas, I've been trying to follow your article How To Create A Universal Vue App With GraphQL but have a problem running the client.

Yarn start or yarn dev on Windows 10 results in the following error:

```
universal-vue-app-with-graphql\middleware\vue-ssr.js:82
  const render = async (req, res) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\Nicky\Source\Repos\vue\universal-vue-app-with-graphql\start.js:2:13)
    at Module._compile (module.js:571:32)
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at notFoundError (D:\Users\Nicky\Source\Repos\vue\universal-vue-app-with-graphql\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\Users\Nicky\Source\Repos\vue\universal-vue-app-with-graphql\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\Users\Nicky\Source\Repos\vue\universal-vue-app-with-graphql\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
error Command failed with exit code 1.

```
Any help greatly appreciated.

**Comment by 1xiyu** [comment]
+1,  appear In the above situation .

**Comment by 1xiyu** [comment]
change a higner node version more than 7.6.0 @Taramouse
